version: '3.8'

services:
  # O Backend (Sua aplicação)
  sollus-backend:
    # container_name: removido (não suportado no Swarm)
    image: ghcr.io/jefrocha/sollus:main
    # build: removido (não suportado no Swarm)
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=sollus-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=SolucionandoTudo
      - DB_DATABASE=solluserp
      - PORT=3000
    depends_on:
      - sollus-db
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sollus-network

  # O Banco de Dados (PostgreSQL)
  sollus-db:
    # container_name: removido
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SolucionandoTudo
      POSTGRES_DB: solluserp
    volumes:
      - sollus_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sollus-network

volumes:
  sollus_pg_data:


networks:
  sollus-network:
    driver: overlay
    attachable: true # Permite que containers standalone também se conectem, se necessário
