version: '3.8'

services:
  # O Backend (Sua aplicação)
  sollus-backend:
    image: ghcr.io/jefrocha/sollus:main
    environment:
      - DB_TYPE=postgres
      - DB_HOST=sollus-db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=SolucionandoTudo
      - DB_DATABASE=solluserp
      - PORT=3000
    depends_on:
      - sollus-db
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        # Habilita o Traefik para este serviço
        - "traefik.enable=true"
        # Define a porta interna do container
        - "traefik.http.services.sollus-backend.loadbalancer.server.port=3000"
        # Configura o roteamento por domínio
        - "traefik.http.routers.sollus-backend.rule=Host(`sollus.sollucoesemgestao.com.br`)"
        # Habilita HTTPS
        - "traefik.http.routers.sollus-backend.entrypoints=websecure"
        - "traefik.http.routers.sollus-backend.tls=true"
        - "traefik.http.routers.sollus-backend.tls.certresolver=letsencryptresolver"
        # Redireciona HTTP para HTTPS (usa o middleware do Traefik)
        - "traefik.http.routers.sollus-backend-http.rule=Host(`sollus.sollucoesemgestao.com.br`)"
        - "traefik.http.routers.sollus-backend-http.entrypoints=web"
        - "traefik.http.routers.sollus-backend-http.middlewares=redirect-https@docker"
    networks:
      - sollus-prod-net
      - minha_rede # Conecta na rede do Traefik

  # O Banco de Dados (PostgreSQL)
  sollus-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SolucionandoTudo
      POSTGRES_DB: solluserp
    volumes:
      - sollus_pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - sollus-prod-net

volumes:
  sollus_pg_data:


networks:
  sollus-prod-net:
    driver: overlay
    attachable: true
  minha_rede:
    external: true # Usa a rede existente do Traefik
